name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          #repository: kaltura/documentation-generator 
          #token: ${{ secrets.LB_GITHUB_ACCESS_TOKEN }} 
          #path: lb
    - run: git clone git@github.com:kaltura/documentation-generator lb
    - run: cd lb && git fetch --all && git tag && git checkout master && npm install -g
    - run: npm install
    - run: ./scripts/build-and-commit.sh
    env:
      CI: true
      LB_GITHUB_ACCESS_TOKEN: ${{secrets.LB_GITHUB_ACCESS_TOKEN}}
      KALT_GITHUB_ACCESS_TOKEN: ${{secrets.KALT_GITHUB_ACCESS_TOKEN}}

