name: Node.js CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: LucyBot-Inc/documentation-generator 
        token: ${{ secrets.LB_GITHUB_ACCESS_TOKEN }} 
        path: lb
    - run: cd lb && git fetch --all && git tag && git checkout v4.8.12 && npm install -g
    - run: npm install
    - run: ./scripts/build-and-commit.sh
    env:
      CI: true
      LB_GITHUB_ACCESS_TOKEN: ${{secrets.LB_GITHUB_ACCESS_TOKEN}}
      KALT_GITHUB_ACCESS_TOKEN: ${{secrets.KALT_GITHUB_ACCESS_TOKEN}}

